2016chubachi/tabitomo

- bin/bundle
- bin/rails
- bin/rake
- bin/setup
- db/schema.rb
bin/bundle
bin/rails
bin/rake
bin/setup 
ruby.exe をruby に変更
> change_settings

- db/seeds.rb
- db/seeds/development/booking_comments.rb
- db/seeds/development/booking_schedules.rb
- db/seeds/development/bookings.rb
- db/seeds/development/city_masters.rb
- db/seeds/development/countries.rb
- db/seeds/development/guide_cities.rb
- db/seeds/development/guide_languages.rb
- db/seeds/development/guides.rb
- db/seeds/development/language_codes.rb
- db/seeds/development/members.rb
- db/seeds/development/messages.rb
- db/seeds/development/travelers.rb
- db/seeds/development/user_reviews.rb
- db/seeds/production/booking_comments.rb
- db/seeds/production/booking_schedules.rb
- db/seeds/production/bookings.rb
- db/seeds/production/city_masters.rb
- db/seeds/production/countries.rb
- db/seeds/production/guide_cities.rb
- db/seeds/production/guide_languages.rb
- db/seeds/production/guides.rb
- db/seeds/production/language_codes.rb
- db/seeds/production/members.rb
- db/seeds/production/messages.rb
- db/seeds/production/travelers.rb
- db/seeds/production/user_reviews.rb
> [add]初期データの追加

- .travis.yml
- app/views/shared/_tab_header.html.erb
- app/views/top/index.html.erb
- config/locales/common/en.yml
- config/locales/common/ja.yml
- config/locales/common/ko.yml
- config/locales/common/zh.yml
タブページ用の共通レイアウト修正、今はtopページに置いてるけど。後は実際のページに移す
> tab layout update second

- Gemfile
- Gemfile.lock
- app/models/member.rb
- config/environments/development.rb
- config/initializers/devise.rb
- config/locales/devise.en.yml
- config/routes.rb
- db/migrate/20161012073814_create_members.rb
- db/migrate/20161021105301_add_devise_to_members.rb
- db/schema.rb
> User registration

- app/views/user_reviews/_booking_schedule.html.erb
- app/views/user_reviews/_form.html.erb
- app/views/user_reviews/edit.html.erb
- app/views/user_reviews/new.html.erb
- app/views/user_reviews/show.html.erb
- config/locales/models/booking_schedule/en.yml
- config/locales/models/booking_schedule/ja.yml
- config/locales/models/booking_schedule/ko.yml
- config/locales/models/booking_schedule/zh.yml
- config/locales/models/user_review/en.yml
- config/locales/models/user_review/ja.yml
- config/locales/models/user_review/ko.yml
- config/locales/models/user_review/zh.yml
> [update]UserReview機能の修正

- config/routes.rb
- db/seeds/development/members.rb
> members db modify

- db/seeds/production/members.rb
added member data to production
> added member data to production

- config/routes.rb
> modified route.rb

- app/views/devise/confirmations/new.html.erb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/mailer/password_change.html.erb
- app/views/devise/mailer/reset_password_instructions.html.erb
- app/views/devise/mailer/unlock_instructions.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/devise/unlocks/new.html.erb
- config/routes.rb
> Member view

- app/controllers/members/confirmations_controller.rb
- app/controllers/members/omniauth_callbacks_controller.rb
- app/controllers/members/passwords_controller.rb
- app/controllers/members/registrations_controller.rb
- app/controllers/members/sessions_controller.rb
- app/controllers/members/unlocks_controller.rb
- config/routes.rb
> member_controllers

- app/controllers/traveler_bookings_controller.rb
- app/models/booking.rb
- app/views/traveler_bookings/edit.html.erb
- app/views/traveler_bookings/index.html.erb
- app/views/traveler_bookings/new.html.erb
- app/views/traveler_bookings/show.html.erb
- app/views/user_reviews/_booking_schedule.html.erb
- config/routes.rb
- db/seeds/development/booking_schedules.rb
- db/seeds/development/bookings.rb
- db/seeds/development/status_masters.rb
- db/seeds/production/booking_schedules.rb
- db/seeds/production/bookings.rb
- db/seeds/production/status_masters.rb
- test/controllers/traveler_bookings_controller_test.rb
旅人用の予約一覧機能（とりあえず版）
予約一覧用に初期データを追加
> [add]旅人用予約一覧機能

- app/controllers/search_guides_controller.rb
- app/views/search_guides/index.html.erb
- config/routes.rb
- test/controllers/search_guides_controller_test.rb
> create serach_guides controller

- config/routes.rb
> routing set modify

- app/controllers/application_controller.rb
- app/controllers/search_guides_controller.rb
- app/models/search/base.rb
- app/models/search/guide.rb
- app/views/layouts/application.html.erb
- app/views/search_guides/_search_box.html.erb
- app/views/search_guides/_search_form.html.erb
- app/views/search_guides/index.html.erb
- config/locales/models/guide/en.yml
- config/locales/models/guide/ja.yml
- config/locales/models/guide/ko.yml
- config/locales/models/guide/zh.yml
- config/locales/models/member/en.yml
- config/locales/models/member/ja.yml
- config/locales/models/member/ko.yml
> search module v1

- app/controllers/star_masters_controller.rb
- app/controllers/user_reviews_controller.rb
- app/helpers/application_helper.rb
- app/models/star_master.rb
- app/views/traveler_bookings/index.html.erb
- app/views/user_reviews/_form.html.erb
- config/routes.rb
- test/controllers/star_masters_controller_test.rb
UserReviewの評価画像をテーブルから取得するように変更
> [update]UserReview機能評価画像の取得

- app/controllers/search_guides_controller.rb
- app/models/search/guide.rb
- app/views/search_guides/_search_form.html.erb
> search module

- app/controllers/application_controller.rb
- app/views/layouts/application.html.erb
- config/initializers/devise.rb
- config/locales/devise.ja.yml
- config/locales/devise.ko.yml
- config/locales/devise.zh.yml
- test/controllers/member_controller_test.rb
- test/fixtures/members.yml
- test/integration/member_test.rb
> added yml files

- Gemfile
- Gemfile.lock
- app/views/layouts/application.html.erb
for test code. Using rspec and capybara.
> added capybara for test

- app/helpers/application_helper.rb
- app/views/search_guides/index.html.erb
image tabに対して、max-widthを252pxの設定を追加しました。
> image tag style update max-width

- db/migrate/20161029065601_add_guide_to_members.rb
- db/schema.rb
added guide parameter to member table for control guide and traveler table.
> added guide parameter

- app/controllers/user_reviews_controller.rb
- app/views/traveler_bookings/index.html.erb
- app/views/user_reviews/_form.html.erb
UserReviewを新規に作成する時に、関連するbooking_id をセットしていなかったがセットするように変更
> [fixed]UserReview新規作成機能の変更

- Gemfile
- Gemfile.lock
- config/locales/models/booking_schedule/ko.yml
- config/locales/models/member/en.yml
- config/locales/models/member/ja.yml
- config/locales/models/member/ko.yml
- config/locales/models/member/zh.yml
added gem for devise internationalization.
> modified member06

- app/controllers/traveler_bookings_controller.rb
- app/models/booking.rb
- app/models/traveler_booking_comment.rb
- app/views/traveler_bookings/edit.html.erb
- app/views/traveler_bookings/index.html.erb
- config/locales/models/booking_schedule/en.yml
- config/locales/models/booking_schedule/ja.yml
- config/locales/models/booking_schedule/ko.yml
- config/locales/models/booking_schedule/zh.yml
- db/migrate/20161030122048_create_traveler_booking_comments.rb
- db/schema.rb
- db/seeds.rb
- db/seeds/development/traveler_booking_comments.rb
- db/seeds/production/traveler_booking_comments.rb
- test/fixtures/traveler_booking_comments.yml
- test/models/traveler_booking_comment_test.rb
旅人用の予約変更画面追加（作成途中）
テーブル追加（traveler_booking_comment)
booking_comment を分けた方が良さそうなので。要相談
> [add]旅人用予約変更画面追加、テーブル追加

- app/assets/stylesheets/application.css
- app/controllers/guide_detail_controller.rb
- app/views/guide_detail/_review_list.html.erb
- db/seeds/development/travelers.rb
> guide detail v3

- app/models/member.rb
- db/migrate/20161012073814_create_members.rb
- db/schema.rb
- db/seeds/development/members.rb
- db/seeds/production/members.rb
modify member part with accessor and seed file.
> modify member part

- app/controllers/guide_bookings_controller.rb
- app/controllers/traveler_bookings_controller.rb
- app/models/traveler.rb
- app/views/guide_bookings/edit.html.erb
- app/views/guide_bookings/index.html.erb
- app/views/guide_bookings/show.html.erb
- app/views/guide_bookings/update.html.erb
- app/views/traveler_bookings/_form.html.erb
- app/views/traveler_bookings/_table.html.erb
- app/views/traveler_bookings/_thumbnail.html.erb
- app/views/traveler_bookings/_thumbnails.html.erb
- app/views/traveler_bookings/edit.html.erb
- app/views/traveler_bookings/index.html.erb
- app/views/user_reviews/_booking_schedule.html.erb
- app/views/user_reviews/_thumbnail.html.erb
- app/views/user_reviews/edit.html.erb
- app/views/user_reviews/new.html.erb
- app/views/user_reviews/show.html.erb
- config/routes.rb
- db/seeds/development/bookings.rb
- db/seeds/production/bookings.rb
- test/controllers/guide_bookings_controller_test.rb
ガイド用の予約一覧機能（作成途中）
旅人用の予約一覧機能のバグ修正
　一覧取得をmemberで取得していたのをtravelerで取るように修正
　check_traveler_booking_editもmemberで取得していたのをtravelerで取るように修正
　viewを部分テンプレートに分割
UserReviewを修正
　写真が固定だったのをmember_pictureから取得するように変更
　
> [add]ガイド用の予約一覧機能（作成途中）

- app/assets/javascripts/application.js
- app/assets/stylesheets/application.css
- app/controllers/guide_detail_controller.rb
- app/views/guide_detail/_calendar.html.erb
- app/views/guide_detail/_review_list.html.erb
- app/views/guide_detail/_review_summary.html.erb
- app/views/guide_detail/_side_left.html.erb
- app/views/guide_detail/_side_right.html.erb
> guide detail module v4

- app/controllers/messages_controller.rb
- test/controllers/messages_controller_test.rb
> messages01

- app/assets/javascripts/application.js
- app/assets/stylesheets/application.css
> bug fix for safari

- app/assets/javascripts/application.js
- app/assets/stylesheets/application.css
- app/controllers/guide_detail_controller.rb
- config/routes.rb
> schedule calendar final

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/controllers/traveler_bookings_controller.rb
- app/views/traveler_bookings/_booking_schedule_fields.html.erb
- app/views/traveler_bookings/_form.html.erb.bk
スケジュールの追加と削除をできるように変更
（とりあえず動いているので、あげます）
> [update]旅人用予約変更画面の変更

- app/assets/javascripts/application.js
- app/assets/stylesheets/application.css
- app/views/guide_detail/_calendar.html.erb
> ng date style modify

- app/assets/stylesheets/application.css
- app/controllers/guide_detail_controller.rb
- app/models/guide_language.rb
- app/views/guide_detail/_booking_button.html.erb
- app/views/guide_detail/_profile.html.erb
- app/views/guide_detail/_side_right.html.erb
- db/seeds/development/language_skills.rb
> guide detail module completed

- db/migrate/20161012073858_create_guides.rb
- db/migrate/20161104074826_change_datatype_birth_year_of_guides.rb
- db/schema.rb
birth_year をinteger から dateに変更
> [Update]Guideのカラム変更

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/stylesheets/application.css
- app/controllers/guide_detail_controller.rb
- app/views/traveler_bookings/_booking_schedule_fields.html.erb
- app/views/traveler_bookings/_form.html.erb
booking詳細の日程にdatepickerを入れました。
> bookings schedule datepicker

- app/controllers/messages_controller.rb
- app/views/messages/index.html.erb
- app/views/messages/show.html.erb
> member03_show_index

- app/assets/javascripts/application.js
> calender cross bug fix

- app/assets/javascripts/application.js
> date bug fix

- app/assets/stylesheets/application.css
- app/controllers/traveler_bookings_controller.rb
- app/models/booking.rb
- app/models/booking_schedule.rb
- app/views/guide_detail/_booking_button.html.erb
- app/views/guide_detail/_booking_button.html.erb.bk
- app/views/traveler_bookings/_booking_schedule_fields.html.erb
- app/views/traveler_bookings/_form.html.erb
- app/views/traveler_bookings/_form.html.erb.bk1
- app/views/traveler_bookings/_thumbnail.html.erb
- app/views/traveler_bookings/_thumbnails.html.erb
- app/views/traveler_bookings/destroy.html.erb
- app/views/traveler_bookings/edit.html.erb
- app/views/traveler_bookings/index.html.erb
- app/views/traveler_bookings/new.html.erb
- app/views/user_reviews/_booking_schedule.html.erb
- db/migrate/20161012074515_create_bookings.rb
- db/schema.rb
- db/seeds/development/bookings.rb
- db/seeds/production/bookings.rb
予約の追加機能を実装
予約の削除機能を実装
bookingテーブルの変更(以下の項目を削除
traveler_first_name,traveler_last_name,traveler_email,city_master_id
> [add]予約の追加・削除を追加、予約テーブル変更

- app/views/layouts/application.html.erb
言語切り替えの際、topページに遷移ではなく、該当ページのままにする
> language change path update current path

- app/views/layouts/application.html.erb
- app/views/shared/_tab_header.html.erb
> tab page url setting

- app/views/shared/_tab_header.html.erb
> tab link path error fix

- app/assets/stylesheets/application.css
- app/controllers/application_controller.rb
- app/controllers/errors_controller.rb
- app/views/errors/error_404.html.erb
- app/views/errors/error_500.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_error.html.erb
- app/views/shared/_info.html.erb
- app/views/top/index.html.erb
- app/views/traveler_bookings/edit.html.erb
- config/application.rb
- config/environments/development.rb
- config/environments/production.rb
- config/routes.rb
バリデーションエラーとインフォメッセージを表示する為の共通モジュール作成
> comm module error area and info area

- config/locales/devise.en.yml
- config/locales/devise.ja.yml
- config/locales/devise.ko.yml
- config/locales/devise.zh.yml
- config/locales/views/member/en.yml
- config/locales/views/member/ja.yml
- config/locales/views/member/ko.yml
- config/locales/views/member/zh.yml
> member12 for delete sign_message

- config/locales/views/member/en.yml
- config/locales/views/member/ja.yml
- config/locales/views/member/ko.yml
- config/locales/views/member/zh.yml
restore member model yml file.
> restore member model

- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- config/locales/devise.ja.yml
modified login session and user registration and other pages.
> modified login screen

- config/locales/base/zh.yml
- config/locales/devise.zh.yml
> global bug fix

- app/controllers/guide_bookings_controller.rb
- config/locales/controllers/guide_bookings/en.yml
- config/locales/controllers/guide_bookings/ja.yml
- config/locales/controllers/guide_bookings/ko.yml
- config/locales/controllers/guide_bookings/zh.yml
> [update]予約一覧（ガイド）の正常時のメッセージ他言語化

- app/views/shared/_info.html.erb
> timedout message delete

- app/views/shared/_info.html.erb
> timedout modify

- .travis.yml
- app/assets/javascripts/application.js
> heroku error fix v2

- app/assets/javascripts/application.js
> heroku error v3

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/stylesheets/application.css
- app/assets/stylesheets/custom.css.scss
- app/helpers/application_helper.rb
- app/views/layouts/application.html.erb
- app/views/traveler_bookings/new.html.erb
１．heroku error調査
２．予約ページに入れないエラー修正
> heroku error v4 and booking page bug fix

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/stylesheets/application.css
- app/assets/stylesheets/custom.css.scss
- app/views/layouts/application.html.erb
heroku error v5修正
予約画面のエラー以外、v4の修正を元に戻した。
v4の修正で、jquery ujsがインポートされないから、ログアウトが作動しない。
> heroku error v5 (v4 modifyed revert)

- app/assets/javascripts/application.js
- app/assets/stylesheets/application.css
> heroku error v6

- app/assets/javascripts/application.js
- app/assets/stylesheets/application.css
> heroku error v7

- app/assets/javascripts/application.js
- app/assets/stylesheets/application.css
- app/views/layouts/application.html.erb
heroku error v8
そして、datepickerの国際化対応
> heroku error and datepicker global setting

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/controllers/application_controller.rb
- app/views/layouts/application.html.erb
- app/views/shared/_header_menu.html.erb
> heroku error and language change

- app/controllers/guides_controller.rb
- app/controllers/members/registrations_controller.rb
- app/controllers/travelers_controller.rb
- app/helpers/application_helper.rb
- app/models/licence_picture.rb
- app/models/member_picture.rb
- app/views/devise/registrations/new.html.erb
- app/views/guides/_form.html.erb
- app/views/shared/_tab_link.html.erb
- app/views/travelers/_form.html.erb
- app/views/travelers/edit.html.erb
- config/locales/models/member/en.yml
- config/locales/models/member/ja.yml
- config/locales/models/member/ko.yml
- config/routes.rb
create traveler profile part and fixed bug.
> Traveler01

- app/assets/javascripts/application.js
- app/assets/stylesheets/application.css
- app/views/guide_detail/_review_list.html.erb
- app/views/shared/_message_groups.html.erb
送受信一覧のタイトルをクリックしたとき、メッセージ詳細をポップアップで表示させる
> Message slide

- app/controllers/messages_controller.rb
- app/controllers/traveler_bookings_controller.rb
- app/models/search/guide.rb
- app/views/guide_detail/_profile.html.erb
- app/views/guide_detail/_side_right.html.erb
#110  検索で大文字、小文字区別しないように
#111  ガイドがログインした場合、ガイド詳細ページからの「予約」、「メッセージ」機能を制限する
> guide booking,message bug and search bug fix

- app/controllers/guide_bookings_controller.rb
- app/controllers/traveler_bookings_controller.rb
- app/views/guide_bookings/index.html.erb
- app/views/kaminari/_first_page.html.erb
- app/views/kaminari/_gap.html.erb
- app/views/kaminari/_last_page.html.erb
- app/views/kaminari/_next_page.html.erb
- app/views/kaminari/_page.html.erb
- app/views/kaminari/_paginator.html.erb
- app/views/kaminari/_prev_page.html.erb
- app/views/traveler_bookings/index.html.erb
- config/initializers/kaminari_config.rb
- config/locales/common/en.yml
- config/locales/common/ja.yml
- config/locales/common/ko.yml
- config/locales/common/zh.yml
> [add]予約一覧にPagination追加

- app/controllers/messages_controller.rb
> message bug fix

- app/views/devise/registrations/new.html.erb
> user sign_up error url path modify

- config/locales/controllers/guide_bookings/ko.yml
- config/locales/controllers/traveler_bookings/ko.yml
- config/locales/controllers/user_reviews/ko.yml
- config/locales/devise.en.yml
- config/locales/devise.ja.yml
- config/locales/devise.ko.yml
- config/locales/devise.zh.yml
- config/locales/models/booking/ko.yml
- config/locales/models/booking_schedule/ko.yml
- config/locales/models/country/ko.yml
- config/locales/models/guide/ko.yml
- config/locales/models/guide_booking_comment/ko.yml
- config/locales/models/member/ko.yml
- config/locales/models/traveler_booking_comment/ko.yml
- config/locales/models/user_review/ko.yml
- config/locales/views/guide/ko.yml
- config/locales/views/member/ko.yml
- config/locales/views/traveler_bookings/ko.yml
- config/locales/views/user_reviews/ko.yml
> internationalization

- app/views/guide_bookings/index.html.erb
- app/views/layouts/application.html.erb
- app/views/top/_slide_header.html.erb
> Footer slide

- app/views/layouts/application.html.erb
- app/views/shared/_header_menu.html.erb
メンバ登録でエラーを発生させてから言語切り替えるとエラーになる問題の修正
> member registration error language change bug fix

- config/locales/devise.en.yml
- config/locales/devise.ja.yml
- config/locales/devise.ko.yml
- config/locales/devise.zh.yml
> modified devise message

- app/assets/stylesheets/application.css
- app/views/guide_bookings/index.html.erb
guide booking 一覧ページのステータス表示をスタンプ式にしました。
> booking status display modify

- app/views/layouts/application.html.erb
> language change bug fix

- app/views/travelers/edit.html.erb
旅人プロフィールページの写真アップロード機能で写真を選択した後、ファイル名も表示するようにした
> traveler image upload display file name

- config/locales/controllers/guide_detail/en.yml
- config/locales/controllers/guide_detail/ko.yml
- config/locales/controllers/guides/en.yml
- config/locales/controllers/guides/ko.yml
- config/locales/controllers/messages/en.yml
- config/locales/controllers/messages/ko.yml
- config/locales/controllers/search_guides/en.yml
- config/locales/controllers/search_guides/ko.yml
- config/locales/controllers/traveler_bookings/ko.yml
- config/locales/models/guide_booking_comment/ko.yml
- config/locales/models/message/en.yml
- config/locales/models/message/ko.yml
- config/locales/views/guides/en.yml
- config/locales/views/guides/ko.yml
- config/locales/views/shared/en.yml
- config/locales/views/shared/ko.yml
> internationalization05

- app/controllers/guides_controller.rb
> modified guide part

- db/seeds/development/language_skills.rb
- db/seeds/development/status_masters.rb
- db/seeds/production/language_skills.rb
> added korean language

- db/seeds/development/city_masters.rb
- db/seeds/production/city_masters.rb
> city master modify

- app/models/licence_picture.rb
- config/locales/common/ko.yml
- config/locales/models/guide/ko.yml
- config/locales/models/message/ko.yml
- config/locales/views/guide_detail/ko.yml
- config/locales/views/guides/ko.yml
- config/locales/views/search_guides/ko.yml
- config/locales/views/shared/ko.yml
- config/locales/views/top/ko.yml
> modified korean

- app/views/devise/passwords/edit.html.erb
> password reset page modified

- app/controllers/application_controller.rb
- config/routes.rb
> modified session and registration

- app/views/messages/_accept_box.html.erb
- app/views/messages/_send_box.html.erb
> close #183

- app/controllers/travelers_controller.rb
- app/helpers/application_helper.rb
- app/views/guide_detail/_review_list.html.erb
> close issues #184

- app/helpers/application_helper.rb
- app/views/guide_detail/_review_list.html.erb
> Issues 185

- app/controllers/guides_controller.rb
- app/controllers/travelers_controller.rb
- app/models/licence_picture.rb
- app/models/member_picture.rb
- config/locales/controllers/guides/en.yml
- config/locales/controllers/guides/ja.yml
- config/locales/controllers/guides/ko.yml
- config/locales/controllers/guides/zh.yml
- config/locales/controllers/travelers/en.yml
- config/locales/controllers/travelers/ja.yml
- config/locales/controllers/travelers/ko.yml
- config/locales/controllers/travelers/zh.yml
写真アップロードエラーの国際化対応
標準のやり方では旅人の方対応できるのですが、
ガイドの方ではいろいろ試しましたが対応できないので、
逃げました。
> Image upload

- app/views/user_reviews/edit.html.erb
- app/views/user_reviews/new.html.erb
- app/views/user_reviews/show.html.erb
- config/locales/views/user_reviews/en.yml
- config/locales/views/user_reviews/ja.yml
- config/locales/views/user_reviews/ko.yml
- config/locales/views/user_reviews/zh.yml
page header の国際化が漏れていたので対応
#205 左記のissue対応
> [fixed]ユーザーレビューの国際化漏れ対応

- app/views/guide_detail/_side_right.html.erb
- app/views/shared/_member_box.html.erb
- app/views/shared/_message_groups.html.erb
- app/views/shared/_new_message.html.erb
> close #192

- app/views/guide_detail/_booking_button.html.erb
- app/views/guide_detail/_profile.html.erb
- app/views/guide_detail/_side_right.html.erb
- app/views/guide_detail/show.html.erb
> close #193

- app/views/guide_detail/_booking_button.html.erb
- app/views/guide_detail/_profile.html.erb
- app/views/guide_detail/_side_left.html.erb
- app/views/guide_detail/_side_right.html.erb
- app/views/guide_detail/show.html.erb
> Issues 198

- app/controllers/application_controller.rb
close #201 
ブラウザの設定言語を読込、パラメータ、セッションともに言語コードがない場合、これを使う
> browser language set input

- app/controllers/application_controller.rb
- config/environments/test.rb
- test/controllers/guide_bookings_controller_test.rb
- test/controllers/guide_detail_controller_test.rb
- test/controllers/guides_controller_test.rb
- test/controllers/member_controller_test.rb
- test/controllers/message_receives_controller_test.rb
- test/controllers/message_sends_controller_test.rb
- test/controllers/messages_controller_test.rb
- test/controllers/msg_accepts_controller_test.rb
- test/controllers/msg_sends_controller_test.rb
- test/controllers/search_guides_controller_test.rb
- test/controllers/star_masters_controller_test.rb
- test/controllers/top_controller_test.rb
- test/controllers/traveler_bookings_controller_test.rb
- test/controllers/user_reviews_controller_test.rb
- test/fixtures/booking_schedules.yml
- test/fixtures/bookings.yml
- test/fixtures/city_masters.yml
- test/fixtures/countries.yml
- test/fixtures/guides.yml
- test/fixtures/members.yml
- test/fixtures/status_masters.yml
- test/fixtures/travelers.yml
- test/integration/member_integration_test.rb
- test/integration/member_test.rb
- test/mailers/traveler_booking_mailer_test.rb
テストの最初のバージョン、メーラーテストを通せるようにした。
> test first version

- config/initializers/devise.rb
- config/locales/models/guide/en.yml
modified setting of timeout and changed English Language.
> modified English and timeout setting

- test/controllers/traveler_bookings_controller_test.rb
- test/fixtures/booking_schedules.yml
- test/fixtures/city_masters.yml
traveler_booking_controllerのテストを追加（途中）
> [add]traveler_booking_controllerのテスト

- app/controllers/guides_controller.rb
- app/controllers/messages_controller.rb
- app/controllers/travelers_controller.rb
- app/views/guides/edit.html.erb
- app/views/messages/new.html.erb
- app/views/shared/_redirect.html.erb
- app/views/travelers/edit.html.erb
close #217 
リダイレクト問題修正
コントローラの方にrenderに戻しました
更新失敗後f5でエラーになる問題を対応するために、
ダミーのリダイレクトを使ってurlを修正する
> close #217

- app/controllers/guides_controller.rb
- app/views/guides/_form.html.erb
- app/views/travelers/_form.html.erb
close #230 
全てのエラー情報を表示できるようにした
> Issues 230

- app/controllers/application_controller.rb
- app/controllers/guide_bookings_controller.rb
- app/controllers/guides_controller.rb
- app/controllers/traveler_bookings_controller.rb
- app/controllers/travelers_controller.rb
- config/locales/common/en.yml
- config/locales/common/ja.yml
- config/locales/common/ko.yml
- config/locales/common/zh.yml
- config/routes.rb
自分と関係のあるデータしかアクセスできないようなチェック追加、他人のデータを見ようとするとき、500エラーにします。
> Access check

- app/assets/stylesheets/application.css
- app/views/search_guides/index.html.erb
ガイド検索結果に改行させないようにしました。
#224 ガイドの検索結果がずれる問題
> guide info display nowrap

- app/assets/stylesheets/application.css
- app/views/shared/_error.html.erb
- app/views/shared/_info.html.erb
> message header modify and guide detail display wrap modify

- app/views/search_guides/index.html.erb
> guide box max height => height

- app/assets/stylesheets/application.css
guide info display wrap modify
> guide info display wrap modify

- app/assets/stylesheets/application.css
- app/views/guide_detail/show.html.erb
- app/views/search_guides/index.html.erb
- app/views/shared/_tab_header.html.erb
> header margin add
